name: CI for pushing to Docker Hub

on:
  push:
#    tags:
#      - v*
    branches:
      - master

jobs:
  push-docker-image:
    name: Push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project
        run: mvn clean package -Dmaven.test.skip=true -B

      - name: Get project version
        run: echo "DOCKER_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/pet-clinic:${{ env.DOCKER_TAG }}
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_IMAGE }}
