# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI for pushing to Docker Hub

on:
  push:
    tags:
      - v*

jobs:
  push-docker-image:
    name: Push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Get project version
        run: |
          DOCKER_TAG=${GITHUB_REF#refs/tags/v} >> $GITHUB_ENV
          echo $DOCKER_TAG
          echo ${{ env.DOCKER_TAG }}