# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]


jobs:
  docs-build-and-deploy:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    env:
      SOURCE_DIR: docs/dir1
      TEMP_DIR: tmp
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # Dependency for AsciiDoctor
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install AsciiDoctor
        uses: reitzig/actions-asciidoctor@v1.0.0

      - name: Convert adoc into html
        run: asciidoctor -o ${DOCS_DESTINATION_FILE} ${DOCS_SOURCE_FILE}
        env:
          DOCS_SOURCE_FILE: ${{ env.SOURCE_DIR }}/some.adoc
          DOCS_DESTINATION_FILE: ${{ env.TEMP_DIR }}/index.html

      # Plantuml needs an absolute path for saving files
      - name: Set veriables
        id: setdirs
        run: |
          echo "::set-output name=source::${PUML_SOURCE_DIR}/**.puml"
          echo "::set-output name=dest::/github/workspace/${PUML_DESTINATION_DIR}"
        env:
          PUML_SOURCE_DIR: ${{ env.SOURCE_DIR }}/puml
          PUML_DESTINATION_DIR: ${{ env.TEMP_DIR }}/images

      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -v -tpng -o ${{ steps.setdirs.outputs.dest }} ${{ steps.setdirs.outputs.source }}

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.TEMP_DIR }}
